import React, { useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import { motion } from "framer-motion";
import { Mail, MapPin, GraduationCap, FileText, Users, ExternalLink, Search, ChevronRight, Sparkles, BriefcaseBusiness, BarChart3, Brain, Award, Scale } from "lucide-react";
import "./index.css";

function Card({ className = "", children }) { return <div className={`rounded-3xl border border-slate-200 bg-white shadow-sm ${className}`}>{children}</div>; }
function CardContent({ className = "", children }) { return <div className={className}>{children}</div>; }
function Button({ asChild, variant = "default", size = "default", className = "", children }) {
  const base = `inline-flex items-center justify-center font-medium transition ${size === "lg" ? "px-5 py-3 text-base" : "px-4 py-2 text-sm"} ${variant === "outline" ? "border border-slate-200 bg-white text-slate-900 hover:bg-slate-50" : variant === "secondary" ? "bg-white text-slate-950 hover:bg-slate-100" : "bg-slate-950 text-white hover:bg-slate-800"} ${className}`;
  if (asChild && React.isValidElement(children)) return React.cloneElement(children, { className: `${base} ${children.props.className || ""}` });
  return <button className={base}>{children}</button>;
}

const researchAreas = [
  { title: "Behavioral Economics and Human Decision-Making", text: "Research on how people behave, form beliefs, respond to information, and make decisions under uncertainty.", icon: Brain },
  { title: "Public Policy and Opportunity", text: "Policy-oriented research on inequality, poverty reduction, development, migration, and ways to expand opportunities for all.", icon: Scale },
  { title: "Neuroeconomics, Morality, and Social Preferences", text: "Interdisciplinary work on morality, moral framing, social preferences, and the cognitive and neural foundations of human decisions.", icon: Users },
  { title: "Behavioral Finance and Narrative-Based Markets", text: "Studies how leader-centered narratives, media sentiment, investor salience, and LLM-based text measures shape belief formation and market reactions.", icon: BarChart3 },
];

const projects = [
  { title: "Donation to Food Banks during Food Security Crises: Experiment on Information Nudges with Intertemporal Giving Choices", authors: "Sunyoung Lee, Pulkit Marwah, Yu Yvette Zhang, and Rodolfo M. Nayga, Jr.", status: "Working paper", tags: ["Charitable Giving", "Information Nudges", "Food Security"], pdf: "/files/donation-food-crisis.pdf", summary: "Examines how deliberate versus impulsive nudges and donation timing shape food bank donation decisions during a food security crisis, using an incentive-compatible experiment." },
  { title: "When Development Enables Exit: Corporate Social Responsibility and Rural Migration Dynamics", authors: "Sunyoung Lee, Darima Zhenskhana, Song Soo Lim, Onggarbek Alipbeki, Aida Balkibayeva, Bakdaulet Kypshakbayev, Gulbanu Appazova, and Tangat Azan", status: "Working paper", tags: ["Development Economics", "CSR", "Migration"], pdf: "/files/kz-csr-migration.pdf", summary: "Studies whether CSR and local amenities help retain rural populations or instead become part of a broader development process that expands mobility in Kazakhstan’s Akmola region." },
  { title: "Leader vs. Firm News Sentiment and Stock Market Reactions", authors: "Sunyoung Lee", status: "Working paper", tags: ["Behavioral Finance", "Narrative Framing", "LLM Sentiment"], summary: "Examines whether identical sentiment has different effects on investor reactions depending on whether it is embedded in leader-centered or firm-centered news narratives." },
  { title: "Behavioral Interventions and Poverty Reduction: A Mechanism-Based Framework", authors: "Sunyoung Lee", status: "Working paper", tags: ["Behavioral Economics", "Poverty Reduction", "Public Policy"], summary: "Develops a mechanism-based framework for understanding how behavioral interventions may support poverty reduction and expand opportunities for disadvantaged communities." },
  { title: "Morality, Framing, and Economic Decision-Making", authors: "Sunyoung Lee", status: "Working paper", tags: ["Neuroeconomics", "Morality", "Experiments"], summary: "Develops interdisciplinary research on moral framing, social preferences, and human decision-making using behavioral experiments and emerging neuroeconomic approaches." },
];

const publications = [
  { citation: "Lee, Sunyoung. \"Did recreational marijuana legalization increase crime in the long run?\" International Review of Law and Economics 82 (2025): 106246.", year: "2025" },
  { citation: "Lee, S., Lim, S. S., & Kimura, S. (2026). Gravity of innovation: how R&D capacity and climate suitability shape international seed potato trade. China Agricultural Economic Review, 1–23.", year: "2026" },
];
const courses = ["Principles of Microeconomics", "Behavioral Economics for Business Strategy", "Business Research & Analytics", "Introduction to Business Analytics", "Entrepreneurial Insights & Korean Trends", "Korean Economy and Business Contexts", "Modern Society and Marketing"];
const methods = ["Behavioral experiments", "Applied econometrics", "Survey design", "LLM-based text and sentiment analysis", "PLS-SEM", "Causal analysis", "Network analysis", "Policy analysis"];

function Section({ id, label, title, intro, children }) {
  return <section id={id} className="scroll-mt-24 py-16 md:py-24"><motion.div initial={{ opacity: 0, y: 18 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, margin: "-80px" }} transition={{ duration: 0.5 }}><div className="mb-8 max-w-3xl"><p className="mb-3 text-sm font-semibold uppercase tracking-[0.25em] text-slate-500">{label}</p><h2 className="text-3xl font-semibold tracking-tight text-slate-950 md:text-4xl">{title}</h2>{intro && <p className="mt-5 text-lg leading-8 text-slate-600">{intro}</p>}</div>{children}</motion.div></section>;
}

function App() {
  const [query, setQuery] = useState("");
  const filteredProjects = useMemo(() => { const q = query.trim().toLowerCase(); if (!q) return projects; return projects.filter((p) => `${p.title} ${p.authors} ${p.status} ${p.tags.join(" ")} ${p.summary}`.toLowerCase().includes(q)); }, [query]);
  return <div className="min-h-screen bg-gradient-to-b from-slate-50 via-white to-slate-100 text-slate-900">
    <header className="sticky top-0 z-50 border-b border-slate-200/80 bg-white/85 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 md:px-8"><a href="#home" className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-2xl bg-slate-950 text-white shadow-sm">SL</div><div><p className="text-sm font-semibold leading-tight">Sunyoung Skylar Lee</p><p className="text-xs text-slate-500">Professor · Hanyang University</p></div></a><nav className="hidden items-center gap-6 text-sm font-medium text-slate-600 md:flex"><a href="#about" className="hover:text-slate-950">About</a><a href="#research" className="hover:text-slate-950">Research</a><a href="#teaching" className="hover:text-slate-950">Teaching</a><a href="#cv" className="hover:text-slate-950">CV</a><a href="#contact" className="hover:text-slate-950">Contact</a></nav><Button asChild className="rounded-2xl"><a href="mailto:syredmoon@gmail.com">Contact</a></Button></div></header>
    <main id="home" className="mx-auto max-w-7xl px-5 md:px-8">
      <section className="grid gap-10 py-16 md:grid-cols-[1.1fr_0.9fr] md:items-center md:py-24"><motion.div initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.55 }}><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-slate-200 bg-white px-4 py-2 text-sm text-slate-600 shadow-sm"><Sparkles className="h-4 w-4" />Behavioral economics · Public policy · Neuroeconomics</div><h1 className="max-w-5xl text-4xl font-semibold tracking-tight text-slate-950 md:text-6xl">Sunyoung Skylar Lee</h1><p className="mt-5 text-2xl font-medium text-slate-700 md:text-3xl">Professor at Hanyang University</p><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-600">I am interested in how people behave and how research can help increase opportunities for all. My work connects behavioral economics, public policy, neuroeconomics, and morality to better understand human decisions in markets, organizations, and society.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Button asChild size="lg" className="rounded-2xl"><a href="#research">Research <ChevronRight className="ml-2 h-4 w-4" /></a></Button><Button asChild size="lg" variant="outline" className="rounded-2xl bg-white"><a href="#teaching">Teaching</a></Button></div></motion.div><motion.div initial={{ opacity: 0, scale: 0.96 }} animate={{ opacity: 1, scale: 1 }} transition={{ duration: 0.55, delay: 0.1 }}><Card className="overflow-hidden rounded-[2rem] shadow-xl shadow-slate-200/60"><CardContent className="p-0"><div className="bg-slate-950 p-8 text-white"><p className="text-sm uppercase tracking-[0.25em] text-slate-300">Academic profile</p><h2 className="mt-4 text-3xl font-semibold">Behavioral Economics & Policy Analysis</h2><p className="mt-3 leading-7 text-slate-300">Research, teaching, and collaboration on human behavior, public policy, morality, and decision science.</p></div><div className="grid gap-4 p-8"><div className="flex gap-4"><GraduationCap className="mt-1 h-5 w-5 text-slate-500" /><div><p className="font-medium">Ph.D. in Agricultural Economics</p><p className="text-sm text-slate-500">Texas A&M University</p></div></div><div className="flex gap-4"><BriefcaseBusiness className="mt-1 h-5 w-5 text-slate-500" /><div><p className="font-medium">Current affiliation</p><p className="text-sm text-slate-500">Hanyang University, Seoul, Korea</p></div></div><div className="flex gap-4"><Award className="mt-1 h-5 w-5 text-slate-500" /><div><p className="font-medium">Research focus</p><p className="text-sm text-slate-500">Behavioral economics, public policy, neuroeconomics, morality, AI-assisted text methods</p></div></div></div></CardContent></Card></motion.div></section>
      <Section id="about" label="About" title="Academic profile" intro="My research is grounded in an interest in how people behave, how human decisions are shaped, and how evidence-based policy can expand opportunities for all."><div className="grid gap-6 md:grid-cols-3"><Card className="md:col-span-2"><CardContent className="p-7"><h3 className="text-2xl font-semibold">Research and teaching interests</h3><p className="mt-4 leading-8 text-slate-600">I work across behavioral economics, public policy, neuroeconomics, and morality in human decision-making. My recent projects use experiments, survey design, econometric analysis, PLS-SEM, and LLM-based text analysis to study investor behavior, narrative framing, poverty reduction, CSR, rural migration, inequality, and moral decision-making.</p><p className="mt-4 leading-8 text-slate-600">Across research and teaching, my broader goal is to understand behavioral mechanisms and use that knowledge to support better decisions, better institutions, and broader opportunity.</p></CardContent></Card><Card><CardContent className="p-7"><MapPin className="h-8 w-8 text-slate-700" /><h3 className="mt-5 text-2xl font-semibold">Affiliation</h3><p className="mt-4 leading-7 text-slate-600">Hanyang University<br />Seoul, Republic of Korea</p></CardContent></Card></div></Section>
      <Section id="research" label="Research" title="Research" intro="My research examines how people behave, how beliefs and moral judgments are formed, and how policy and institutional environments can expand or constrain opportunities."><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-4">{researchAreas.map((area) => { const Icon = area.icon; return <Card key={area.title} className="transition hover:-translate-y-1 hover:shadow-lg"><CardContent className="p-6"><div className="mb-5 flex h-12 w-12 items-center justify-center rounded-2xl bg-slate-100"><Icon className="h-6 w-6 text-slate-700" /></div><h3 className="text-lg font-semibold tracking-tight text-slate-950">{area.title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{area.text}</p></CardContent></Card>; })}</div><div className="mt-14"><h3 className="text-2xl font-semibold tracking-tight text-slate-950">Publications</h3><div className="mt-5 grid gap-4">{publications.map((pub) => <Card key={pub.citation}><CardContent className="grid gap-3 p-6 md:grid-cols-[90px_1fr]"><div className="text-sm font-semibold text-slate-500">{pub.year}</div><p className="leading-7 text-slate-700">{pub.citation}</p></CardContent></Card>)}</div></div><div className="mt-14"><h3 className="text-2xl font-semibold tracking-tight text-slate-950">Working papers</h3><div className="mt-5 mb-7 flex flex-col gap-3 rounded-3xl border border-slate-200 bg-white p-4 shadow-sm md:flex-row md:items-center"><Search className="h-5 w-5 text-slate-400" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search working papers by topic, method, or keyword" className="w-full bg-transparent text-sm outline-none placeholder:text-slate-400" /></div><div className="grid gap-5 md:grid-cols-2">{filteredProjects.map((project) => <Card key={project.title} className="transition hover:-translate-y-1 hover:shadow-lg"><CardContent className="p-7"><div className="mb-4 flex items-center justify-between gap-4"><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-medium text-slate-600">{project.status}</span></div><h3 className="text-xl font-semibold tracking-tight text-slate-950">{project.title}</h3><p className="mt-2 text-sm font-medium text-slate-500">{project.authors}</p><p className="mt-3 leading-7 text-slate-600">{project.summary}</p><div className="mt-5 flex flex-wrap gap-2">{project.tags.map((tag) => <span key={tag} className="rounded-full border border-slate-200 px-3 py-1 text-xs text-slate-600">{tag}</span>)}</div>{project.pdf && <div className="mt-5"><Button asChild variant="outline" className="rounded-2xl"><a href={project.pdf} target="_blank" rel="noreferrer">View PDF <ExternalLink className="ml-2 h-4 w-4" /></a></Button></div>}</CardContent></Card>)}</div></div></Section>
      <Section id="teaching" label="Teaching" title="Courses" intro="My teaching spans economics, behavioral decision-making, business research, analytics, entrepreneurship, and Korean economic contexts."><div className="grid gap-3 md:grid-cols-2">{courses.map((course) => <div key={course} className="flex items-center justify-between rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><span className="font-medium text-slate-800">{course}</span><ChevronRight className="h-4 w-4 text-slate-400" /></div>)}</div></Section>
      <Section id="cv" label="CV & Methods" title="Academic background and methods" intro="My work draws on behavioral theory, applied empirical methods, and interdisciplinary approaches to decision-making."><div className="grid gap-6 md:grid-cols-3"><Card className="md:col-span-2"><CardContent className="p-7"><h3 className="text-2xl font-semibold">Methods and tools</h3><div className="mt-6 grid gap-3 sm:grid-cols-2">{methods.map((method) => <div key={method} className="rounded-2xl bg-slate-50 px-4 py-3 text-sm font-medium text-slate-700">{method}</div>)}</div></CardContent></Card><Card className="bg-slate-950 text-white"><CardContent className="p-7"><FileText className="h-8 w-8 text-slate-300" /><h3 className="mt-5 text-2xl font-semibold">CV</h3><p className="mt-4 leading-7 text-slate-300">Add downloadable CV, publication list, Google Scholar, ORCID, and working paper links here.</p><Button variant="secondary" className="mt-6 rounded-2xl" asChild><a href="#contact">Request CV</a></Button></CardContent></Card></div></Section>
      <Section id="contact" label="Contact" title="Contact and collaboration" intro="I welcome conversations about research collaboration, student advising, invited talks, and academic exchange."><Card className="rounded-[2rem] shadow-xl shadow-slate-200/60"><CardContent className="grid gap-8 p-8 md:grid-cols-[1fr_auto] md:items-center"><div><h3 className="text-2xl font-semibold text-slate-950">Get in touch</h3><p className="mt-3 max-w-2xl leading-8 text-slate-600">For research collaboration, invited lectures, student advising, or academic inquiries, please contact me by email.</p><div className="mt-5 flex flex-wrap gap-3 text-sm text-slate-600"><span className="inline-flex items-center gap-2 rounded-full bg-slate-100 px-4 py-2"><Mail className="h-4 w-4" /> syredmoon@gmail.com</span><span className="inline-flex items-center gap-2 rounded-full bg-slate-100 px-4 py-2"><MapPin className="h-4 w-4" /> Seoul, Korea</span></div></div><Button asChild size="lg" className="rounded-2xl"><a href="mailto:syredmoon@gmail.com">Email me <ExternalLink className="ml-2 h-4 w-4" /></a></Button></CardContent></Card></Section>
    </main><footer className="border-t border-slate-200 bg-white"><div className="mx-auto flex max-w-7xl flex-col gap-3 px-5 py-8 text-sm text-slate-500 md:flex-row md:items-center md:justify-between md:px-8"><p>© {new Date().getFullYear()} Sunyoung Skylar Lee. All rights reserved.</p><p>Research · Teaching · Public Policy</p></div></footer>
  </div>;
}

createRoot(document.getElementById("root")).render(<App />);
